what:
    name: ENC[AES256_GCM,data:6DuC7IzSxIL363VPTuVZyR2O1KlcLYACDnqSN+YhRnFpFapJNKw+YuYOQu6zYA==,iv:Tan/9qwX7IxqIEyp36fNzRlzqhRchErExNMbkk8VSXs=,tag:EWracI7cG3gTfhsu3cRX2A==,type:str]
    other: ENC[AES256_GCM,data:DgQj,iv:9n4GAenj/8jEGLeBrNMuo83RqTygg/4YoiSEARheU6Q=,tag:oFE1HQYd46rJzXBDFT1ROA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8uqdckfcluvmsvehn2garwk9knsh5pe6lt65fhwwwywpq3czu7qpct257
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNlRmRUNqNW4xQVNQTWN4
            YjRCSEszWVVlYmRZMXlPMDQxOHFmVGpyM1c4CnNMR05zK0JUU2VmSHVwTGw3blNO
            RWIrd2hxRDVQTWRhYzZGZ3FUQWNJM3MKLS0tIHB2cjFlS2N4aGNlY21obzdwRG1h
            Rlc3NlgzWFhRU2p5MTRRZGt3S2g2dmcKeCqBa7Qo8ICyIjqNEs6xZU1uvWL4Iv39
            /wTwgdHyRNqEgWNrPoTLDO1mNEMFWjIOWttPnaZzRbx6v/GOhwYlZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T16:14:35Z"
    mac: ENC[AES256_GCM,data:hjKoFj86L4nKMrdc8i/IgHPmnTmz7fdAK0r59jMqQzK+K297Pxzr46LWOrhbZdk2eABOpn3BprZ4VOziPdIbVqEFB8pQFvIXnUgqWffBh3mx09w2guyNAGjeag8cw59pZAZOUYo5mO4UouA5HWGB11BPyS/vpcXkum8XtPuocIY=,iv:azJQKPvRwjJIioiX0FMN4dYJlJQQfweyqF/d3+3PBAw=,tag:G+ZYnjM12IbHSe9PRMof4g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
